### ISSUE TITLE
Motor wire protector interferes with bracket

### ISSUE THREAD

**Issue by baccula** [sjev/eggcess#1]
Using generic 28BYJ-48 stepper purchased from Amazon, I am unable to correctly seat the motor in the bracket. The (blue on my motor) plastic wiring cover interferes with the bracket recess on both sides. See attached picture for reference.

I would be happy to adjust the model if you are willing to share the CAD?
![image2](https://github.com/sjev/eggcess/assets/22080883/7b43d6fd-d732-4337-9af0-344040cf2d17)

**Comment by sjev** [comment]
Thanks for mentioning this. I had the same issue, so I just filed of the interfering parts of the motor, took less time than to adust the model ;-).

You are very welcome to change the model, it is found on onshape:
https://cad.onshape.com/documents/9d1e9d13503836a93d923c99/w/cf41e9abcfc58e38551d4ef1/e/91ab2b97868868ebff4768e5?renderMode=0&uiState=6590590c9a15484af8e68a46

Not sure how forking/merging for cad models work, lets find out!

**Comment by baccula** [comment]
Thank you for the Onshape link. I don't have much familiarity with Onshape, so I think I will follow your lead and file the motor cover down. Thanks for sharing your design and code too, great work!
